config/routes.rb
Rails.application.routes.draw do
  
  resources :questions
 
  get "/", to: 'application#home'
  root 'application#home'
  resources :moves
  resources :generations
  resources :pokemons

  resources :users

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/move.rb
class Move < ApplicationRecord
    belongs_to :generation
    has_many :pokemon_moves
    has_many :pokemons, through: :pokemon_moves

    validates :name, presence: true
    validates :accuracy, presence: true, numericality: { only_integer: true , greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
    # validates :effect_chance, presence: true, numericality: { only_integer: true , greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
    validates :pp, presence: true, numericality: { only_integer: true , greater_than_or_equal_to: 0}
    validates :priority, presence: true, numericality: { only_integer: true , greater_than_or_equal_to: 0}
    validates :power, presence: true, numericality: { only_integer: true , greater_than_or_equal_to: 0}
    validates :effect, presence: true
    
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :current_move, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticated
  def index
    @moves = Move.all
    @search = params["search"]
    if @search.present?
        @name = @search["name"]
        @moves = Move.where("name LIKE ?", "%#{@name}%")
    end
  end

  def show
    @generation = @move.generation
  end

  def new
    @move = Move.new
    @pokemons = Pokemon.all
    @generations = Generation.all
  end

  def create
    @move = Move.new(move_params)

    if @move.valid?
      @move.save
      redirect_to @move
    else
      flash[:error] = @move.errors.full_messages
      redirect_to new_move_path
    end
  end

  def edit
    @pokemons = Pokemon.all
    @generations = Generation.all
  end

  def update
    @move.update(move_params)
    redirect_to @move
  end

  def destroy
  end

  private

  def current_move
    @move = Move.find(params[:id])
  end

  def move_params
    params.require(:move).permit(
      :name,
      :accuracy,
      :effect_chance,
      :pp,
      :priority,
      :power,
      :search,
      :effect,
      :generation_id,
      :pokemon_ids => []
    )
  end
  
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<% if flash[:error] %>
<% flash[:error].each do |e| %>
<p><%= e %></p>
<%end%>
<%end%>

<%= form_for @move do |f| %>
<%= f.label "Name:" %>
<%= f.text_field :name %>
<br />
<%= f.label "Accuracy:" %>
<%= f.number_field :accuracy %>
<br />
<%= f.label "Effect Chance:" %>
<%= f.number_field :effect_chance %>
<br />
<%= f.label "PP:" %>
<%= f.number_field :pp %>
<br />
<%= f.label "Priority:" %>
<%= f.number_field :priority %>
<br />
<%= f.label "Power:" %>
<%= f.number_field :power %>
<br />
<%= f.label "Effect:" %>
<%= f.text_field :effect %>
<br />
<%= f.label "Generation:" %>
<%= f.collection_select :generation_id, @generations, :id , :name %> 
<br/>
<%= f.label "Pokemon:" %>
<%= f.collection_check_boxes :pokemon_ids, @pokemons, :id , :name %> 
<br/>
<%= f.submit %>
<% end %> 

app/views/moves/edit.html.erb
<%= render "form" %>

<%= form_tag("/moves/#{@move.id}", method: "delete") do %>
<%= submit_tag("Delete Move")%>
<% end %>

app/views/moves/index.html.erb
<%= stylesheet_link_tag "pokemons" %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 offset-sm-2">
    <h1><%=link_to "Moves", moves_path %></h1>
      <hr>
      <%= simple_form_for :search, url: moves_path, method: "GET", html: { class: 'form-inline' } do |f| %>
        <%= f.input :name, input_html: {value: ""} %>
        <%= f.submit "Search", class: "btn btn-primary" %>
      <% end %>
      <% @moves.each do |move| %>
        <h3><%= link_to move.name, move_path(move) %></h3>
      <% end %>
      <br><br>
      <%= link_to "Home", root_path %>
      <%= link_to "Pokemon", pokemons_path %>
    </div>
  </div>
</div>

app/views/moves/new.html.erb
<%= render "form" %>

app/views/moves/show.html.erb
<h1><%=@move.name%></h1>
<h3>Stats</h3>
<ul>
<li>Accuracy: <%=@move.accuracy%></li>
<li>Effect Chance: <%= @move.effect_chance %></li>
<li>PP: <%= @move.pp %></li>
<li>Priority: <%= @move.priority %></li>
<li>Power: <%= @move.power %></li>
<li>Effect: <%= @move.effect %></li>
<li>Generation: <%= @generation.name %>
</ul>

<p>Pokemon Who Learn <%= @move.name %>:</p>
<ul>
<% @move.pokemons.each do |pokemon| %>
<li>
    <%= link_to pokemon.name, pokemon_path(pokemon) %>
</li>
<%end%>
<%= link_to "Home", root_path %>
<%= link_to "Back", pokemons_path %>
</ul>