config/routes.rb
Rails.application.routes.draw do
  
  resources :questions
 
  get "/", to: 'application#home'
  root 'application#home'
  resources :moves
  resources :generations
  resources :pokemons

  resources :users

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticated
  
    def current_user
      if session[:user_id]
        @user = User.find(session[:user_id])
      else
        #nil
      end
    end
  
    def logged_in?
      # if current_user
      #   true
      # else
      #   false
      # end
  
      !!current_user
    end
  
    def authenticated
      redirect_to login_path unless logged_in?
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<!-- Page Content -->
    <div class="container">
     <%= stylesheet_link_tag "home" %>
     
      <!-- Page Heading -->
      <a class="navbar-brand" href="#">
          <img src="">
        </a>
      <h1 class="my-4">Professor Oak's Handbook</h1>

      <!-- Project One -->
      <div class="row">
        <div class="col-md-7">
          <a href="#">
            <img class="img-fluid rounded mb-3 mb-md-0" src="http://www.barraques.cat/imgdirs/big/13/130331_pokemon-wallpaper-hd-download.jpg" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Pokemon</h3>
          <p>Wanna catch em all? You need to know it all! Start studying up on all the Pokemon you know and love right here!</p>
          <a class="btn btn-primary" href="http://localhost:3000/pokemons">Browse Pokemon</a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Two -->
      <div class="row">
        <div class="col-md-7">
          <a href="#">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://usercontent2.hubstatic.com/14165781.png" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Moves</h3>
          <p>Learn about the super powers that pack a fiery punch or send an icy chill down your spine... See what each move does and which of your Pokemon can learn these moves! </p>
          <a class="btn btn-primary" href="http://localhost:3000/moves">View Moves</a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Three -->
      <div class="row">
        <div class="col-md-7">
          <a href="#">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://i.pinimg.com/originals/5b/a4/30/5ba430fc3dcb7bf318c41dc71bff96fd.jpg" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h3>Quiz</h3>
          <p>Think you have what it takes to be a Pokemon master? It's one thing to have the best team, but you need the brains to compliment that brawn! See how well you really know your stuff!</p>
          <a class="btn btn-primary" href="http://localhost:3000/questions/new">Quiz Me!</a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      <!-- Project Four -->
      <div class="row">

       
        <div class="col-md-5">
          <a class="btn btn-primary" <%= link_to 'Logout', sessions_path, method: "delete" %></a>
        </div>
      </div>
      <!-- /.row -->

      <hr>

      
    </div>
    <!-- /.container -->

app/views/application/test_home.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="#">
          <img src="http://placehold.it/150x50?text=Logo" alt="">
        </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
    </div>
  </div>












<!-->
<%= stylesheet_link_tag "home" %>

<div class="container">
    <p id="notice">
        <%= notice %>
    </p>

    <h1>Welcome to Professor Oak's Handbook!</h1>
    <p> Please select your browsing category:</p>

    <p>
        <strong><%= link_to 'Pokemon', pokemons_path %></strong>
    </p>

    <p>
        <strong><%= link_to 'Moves', moves_path %></strong>
    </p>

    <p>
        <strong><%= link_to 'Quiz time!', new_question_path %></strong>
    </p>

    <p>
        <strong><%= link_to 'Logout', sessions_path, method: "delete" %></strong>
    </p>

</div>